In [42]:
import torch
from torchvision.datasets import CIFAR10
import torchvision.transforms as transforms
import numpy as np

In [50]:
trans = transforms.Compose([
        transforms.ColorJitter(0.4, 0.4, 0.4, 0.4),
        transforms.ToTensor(),
        transforms.Normalize([0.49139961, 0.48215843, 0.44653216], [0.24703216, 0.2434851 , 0.26158745])
])

In [51]:
dataset_train = CIFAR10('../../dataset/', train=True, transform=trans)
dataset_test = CIFAR10('../../dataset/', train=False, transform=trans)

In [52]:
len(dataset_test)

10000

In [53]:
dataset_train[0]

(tensor([[[-1.0526e+00, -1.3066e+00, -1.1955e+00,  ...,  5.1899e-01,
            4.2375e-01,  3.6025e-01],
          [-1.7352e+00, -1.9892e+00, -1.7035e+00,  ..., -3.6621e-02,
           -1.0012e-01, -5.2496e-02],
          [-1.5923e+00, -1.7352e+00, -1.2114e+00,  ..., -1.1600e-01,
           -8.4246e-02, -2.5887e-01],
          ...,
          [ 1.3127e+00,  1.2016e+00,  1.1540e+00,  ...,  5.5074e-01,
           -1.1002e+00, -1.1479e+00],
          [ 8.6824e-01,  7.5712e-01,  9.6349e-01,  ...,  9.3174e-01,
           -4.4936e-01, -6.7161e-01],
          [ 8.2061e-01,  6.7774e-01,  8.5236e-01,  ...,  1.4397e+00,
            4.0787e-01, -3.6621e-02]],
 
         [[-9.8167e-01, -1.2394e+00, -1.2072e+00,  ...,  1.4575e-01,
            3.3011e-02,  1.6905e-02],
          [-1.6581e+00, -1.9802e+00, -1.8514e+00,  ..., -5.6291e-01,
           -6.4344e-01, -5.7902e-01],
          [-1.5937e+00, -1.8675e+00, -1.5454e+00,  ..., -6.2733e-01,
           -6.2733e-01, -8.0450e-01],
          ...,
    

In [23]:
temp = torch.zeros((3, 32, 32))
for data in dataset_train:
    temp += data[0]

In [27]:
temp = temp / len(dataset_train)

In [39]:
torch.sum(torch.sum(temp, 1), 1) / (32 * 32) * 255

tensor([125.3069, 122.9504, 113.8657])

In [ ]:
torch.sum

In [ ]:
torch.std()

In [31]:
torch.mean(temp, 2).size()

torch.Size([3, 32])

In [21]:
dataset_train[0][0].size()

torch.Size([3, 32, 32])

In [43]:
mean = np.array([125.3069, 122.9504, 113.8657])
std = np.array([62.9932, 62.0887, 66.7048])

In [46]:
mean_norm = mean / 255
std_norm = std / 255

In [47]:
mean_norm

array([0.49139961, 0.48215843, 0.44653216])

In [48]:
std_norm

array([0.24703216, 0.2434851 , 0.26158745])