In [25]:
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
import sys
sys.path.append('../')
import torchvision
from torchvision.datasets import CIFAR10
from models.network_util import init_net
import torchvision.transforms as transforms
from collections import OrderedDict
from models.network_util import init_weights
from torch.optim import SGD
# import configs.base_config

In [2]:
%reload_ext autoreload
%autoreload 2

In [3]:
from models.resnet_cifar import Resnet50

model = Resnet50()

In [6]:
model.parameters()

<generator object Module.parameters at 0x0000021D736E1048>

In [45]:
bn_params = []
without_bn_params = []
for modu in model.modules():
    print(modu.__class__.__name__)
    classname = modu.__class__.__name__
    if classname.find('BatchNorm') != -1:
        bn_params.append(modu.parameters())
    else:
        without_bn_params.append(modu.parameters())

Resnet50
Sequential
Conv2d
BatchNorm2d
ReLU
Sequential
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU
Sequential
Conv2d
BatchNorm2d
Sequential
Conv2d
BatchNorm2d
ReLU
Conv2d
BatchNorm2d
BuildingBlock
ReLU

In [54]:
bn_params[0]

<generator object Module.parameters at 0x0000021D73A90728>

In [56]:
bn_params = []
without_bn_params = []
for name, param in model.named_parameters():
    if name.find('bn') != -1:
        bn_params.append(param.data)
    else:
        without_bn_params.append(param.data)

In [61]:
SGD([
    {'params': bn_params},
    {'params': without_bn_params}
], lr=1e-3)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.001
    momentum: 0
    nesterov: False
    weight_decay: 0

Parameter Group 1
    dampening: 0
    lr: 0.001
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [40]:
p1 = [{'params': bn_params[i], 'weight_decay':0} for i in range(len(bn_params))]

In [41]:
p2 = [{'params': without_bn_params[i]} for i in range(len(without_bn_params))]

In [42]:
p1.extend(p2)

In [44]:
without_bn_params

[<generator object Module.parameters at 0x0000021D739E35C8>,
 <generator object Module.parameters at 0x0000021D739E32B0>,
 <generator object Module.parameters at 0x0000021D739E3CA8>,
 <generator object Module.parameters at 0x0000021D739E3E60>,
 <generator object Module.parameters at 0x0000021D739E3990>,
 <generator object Module.parameters at 0x0000021D739E3F10>,
 <generator object Module.parameters at 0x0000021D739E3888>,
 <generator object Module.parameters at 0x0000021D739E36D0>,
 <generator object Module.parameters at 0x0000021D73A720A0>,
 <generator object Module.parameters at 0x0000021D739E37D8>,
 <generator object Module.parameters at 0x0000021D73A721A8>,
 <generator object Module.parameters at 0x0000021D73A72258>,
 <generator object Module.parameters at 0x0000021D73A722B0>,
 <generator object Module.parameters at 0x0000021D739E3F68>,
 <generator object Module.parameters at 0x0000021D73A72150>,
 <generator object Module.parameters at 0x0000021D73A72360>,
 <generator object Modul

In [43]:
SGD(p2, lr=1e-3)

ValueError: some parameters appear in more than one parameter group

In [24]:
model.stages.

Sequential(
  (0): BuildingBlock(
    (relu): ReLU()
    (residual): Sequential(
      (res_conv): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
      (res_bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (build_block): Sequential(
      (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (bn1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu1): ReLU()
      (conv2): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (bn2): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (1): BuildingBlock(
    (relu): ReLU()
    (residual): Sequential(
      (res_conv): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
      (res_bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (build_block): Sequential(
      (conv1): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), pad

In [15]:
for modu in model.modules():
    if hasattr(modu, 'bn2'):
        print(modu.bn2.weight.data)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0

In [45]:
model.apply(lambda m: print(m))

Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
ReLU()
Sequential(
  (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU()
)
ReLU()
Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
Sequential(
  (res_conv): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
  (res_bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)
Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
ReLU()
Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
Sequential(
  (0): Conv2d(16, 16, kernel_size=(3, 3), s

Resnet50(
  (first_layer): Sequential(
    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
  )
  (stages): Sequential(
    (0): BuildingBlock(
      (relu): ReLU()
      (residual): Sequential(
        (res_conv): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
        (res_bn): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (build_block): Sequential(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
        (3): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (4): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BuildingBlock(
      (relu): ReLU()
      (residual): Sequential(
        (res_conv

In [23]:
init_weights(model)

initialize network with normal
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear weight
find batch norm
find conv or linear wei

In [24]:
for module in model.children():
    classname = module.__class__.__name__
    print(classname.find('Conv'))

-1
-1
-1
-1


In [14]:
module.__class__.__name__.find

-1

In [9]:
transformation = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop((32, 32), 4),
    transforms.ToTensor()
])
dataset = CIFAR10('../../dataset/', train=True, transform=transformation, download=True)

Files already downloaded and verified


In [10]:
dataloader = DataLoader(dataset, batch_size=)

In [12]:
init_net(model)

initialize network with normal


Resnet50(
  (first_layer): Sequential(
    (0): Conv2d(3, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
  )
  (stages): Sequential(
    (0): BuildingBlock(
      (relu): ReLU()
      (residual): Sequential(
        (0): Conv2d(16, 16, kernel_size=(1, 1), stride=(1, 1))
        (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (build_block): Sequential(
        (0): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (1): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
        (3): Conv2d(16, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
        (4): BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (1): BuildingBlock(
      (relu): ReLU()
      (residual): Sequential(
        (0): Conv2d(16, 16, k

In [26]:
for i, (img, label) in enumerate(dataloader):
    print(img.size())
    if i > 3:
        break

torch.Size([1, 3, 32, 32])
torch.Size([1, 3, 32, 32])
torch.Size([1, 3, 32, 32])
torch.Size([1, 3, 32, 32])
torch.Size([1, 3, 32, 32])
